[tool.poetry]
name = "cta_tracker"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.11"
flask = "3.1.0"

[build-system]
requires = ["poetry-core~=1.0"]
build-backend = "poetry.core.masonry.api"